name: Flask CI/CD

on:
  push:
    branches:
      - main # Brance

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Gantikan dengan perintah untuk menjalankan tes aplikasi Anda
          echo "Run your tests here"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add server SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan 178.128.98.173 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Set up SSH deployment key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Droplet
        run: |
          echo "Deploying to server..."
          rsync -avz --delete --exclude '.git*' --exclude 'README.md' --exclude 'LICENSE' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:development/ml-hoax-detector-api
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd development/ml-hoax-detector-api && docker-compose down && docker compose up -d"
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
